_BASE_: ../maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2ConvNeXt"
  CONVNEXT:
    DEPTHS: [3, 3, 27, 3]
    DIMS: [128, 256, 512, 1024]
    DROP_PATH_RATE: 0.4
    LAYER_SCALE_INIT_VALUE: 1.0
    OUT_INDICES: [0, 1, 2, 3]
  WEIGHTS: "convnext_base_22k_1k_384.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 640) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 2560
  MAX_SIZE_TEST: 2560
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 640  # used in dataset mapper
  FORMAT: "RGB"

TEST:
  EVAL_PERIOD: 2500
  AUG:
    ENABLED: False
    MIN_SIZES: [320, 480, 640, 800, 960, 1120]
    MAX_SIZE: 4480
    FLIP: True
SOLVER:
  CHECKPOINT_PERIOD: 2500
